# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13z8e_-zVg5A_ZpPl5FMLecj-fD28uKCk
"""

import streamlit as st
from transformers import pipeline

st.set_page_config(page_title="Amazon Reviews Sentiment Analysis", page_icon="🛍️")
st.title("🛍️ Amazon Reviews Sentiment Analysis")
st.markdown("""
This application uses a **RoBERTa-base** model fine-tuned on a balanced Amazon Reviews dataset.
The model recognizes three classes: Negative, Neutral, and Positive.
""")

model_path = "mlklt3/amazon-sentiment-roberta-base"

@st.cache_resource
def load_pipeline():
    return pipeline("sentiment-analysis", model=model_path)

try:
    classifier = load_pipeline()
    text = st.text_area("Enter the review text in English:", "This product is amazing, I love it!")

    if st.button("Analyze"):
        if text:
            result = classifier(text)[0]
            label = result['label']
            score = result['score']

            label_map = {"LABEL_0": "NEGATIVE 🔴", "LABEL_1": "NEUTRAL ⚪", "LABEL_2": "POSITIVE 🟢"}
            friendly_label = label_map.get(label, label);

            st.subheader(f"Result: {friendly_label}")
            st.info(f"Model Confidence: {score:.2%}")
        else:
            st.warning("Please enter some text to analyze.")
except Exception as e:
    st.error(f"Failed to load the model. Please ensure your username and model name are correct. Error: {e}")

